name: test linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: configure cmake
      run: >
        cmake -S "${{github.workspace}}/test"
        -B "${{github.workspace}}/build"
        -C "${{github.workspace}}/cmake/common.cmake"
        -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"
        -DORBI_PEDANTIC=ON

    - name: build
      run: cmake --build "${{github.workspace}}/build" -j

    - name: test
      run: "${{github.workspace}}/build/test"
