name: test windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: NcStudios/VulkanCI@v1.1

    - name: configure cmake
      run: >
        cmake -S "${{github.workspace}}/test"
        -B "${{github.workspace}}/build"
        -C "${{github.workspace}}/cmake/common.cmake"
        -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"
        -DORBI_PEDANTIC=ON

    - name: build
      run: cmake --build "${{github.workspace}}/build" -j

    - name: test | just ignore *Debug* here, this just NEEDED
      run: "${{github.workspace}}/build/Debug/test"
